version: "3"
services:
  jupypter:
      image: continuumio/anaconda3
      command: jupyter notebook --ip 0.0.0.0 --port 8888 --allow-root
      volumes:
        - .:/albert
      ports:
        - 8888:8888
      container_name: albert_jupyter